### ISSUE TITLE
Panic when using Editor State ressource

### ISSUE THREAD

**Issue by Ptipiak** [jakobhellermann/bevy_editor_pls#49]
Hi, 
I started to play around with Bevy and Bevy inspector, but I'm hitting an issue with the simplest working example.

```bash
INFO bevy_editor_pls_default_windows::cameras: Spawning editor cameras
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_editor_pls_default_windows-0.2.0/src/cameras/camera_3d_free.rs:130:18
```
Here the code:

```rust
use bevy::prelude::*;
use bevy_editor_pls::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(EditorPlugin)
        .add_system(bevy::window::close_on_esc)
        .run();
}
```

As I said, it's a pretty minimal exemple, so I get that's pretty wide in terms of possible issue and possibly non solvable.

<details>
<summary>here the full stack</summary>
<pre>
<code>
2022-12-02T17:27:40.156550Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2022-12-02T17:27:40.221023Z  WARN bevy_ecs::schedule::graph_utils: bevy_editor_pls_default_windows::debug_settings::fake_time::pause_time wants to be after unknown label: TimeSystem
2022-12-02T17:27:40.221203Z  INFO bevy_editor_pls_default_windows::cameras: Spawning editor cameras
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_editor_pls_default_windows-0.2.0/src/cameras/camera_3d_free.rs:130:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</code>
</pre>
</details>

Here a minimal working example which narrow the issue:
```rust
use bevy::prelude::*;
use bevy_editor_pls_core::EditorState;
use bevy::window::CursorGrabMode;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_system(test_editor)
        .run();
}

fn test_editor(
    editor_state: Res<EditorState>,
) {
    if !editor_state.active {
        return;
    }
}
```

**Comment by Piturnah** [comment]
This should be fixed by #50
